### ISSUE TITLE
Draw Sequence Diagram for Following User

### ISSUE THREAD

**Issue by meminciftci** [bounswe/bounswe2024group11#151]
# 🧱 Description

The sequence diagram for following a user needs to be explicitly shown.

## 📋 Acceptance Criteria

- [ ] Sequence diagram for following a user is on Wiki.

**Comment by ArdaVural** [comment]
We have updated Follow User Sequence Diagram but we encountered some issues.
    Some of the methods are missing or we could not find it. (such as following and follower list update method in Profile class for database)
    After updating following list, we encountered a design choice problem about updating follower list of the target user because following list and follower list has different target users. (This issue is going to be detailed in the tomorrow's meeting.)

@tenacke

**Comment by tenacke** [comment]
I have added Profiles class to access a specific profile by giving the username as input. But I think this class is redundant since it is possible to reach any user with Users class and so to its profile (Profile is a field of the User). Follow user sequence diagram should show the exact path along the following process. I have a path in my mind:
1. User gives directive to follow another user.
2. System reaches the User class instance of both follower and followee by calling Users.find() method.
3. System checkes whether the followee is blocking the follower.
4. System reaches Profile instance (which is the field of the User instance) of the follower.
5. System adds followee to the following list in the Profile instance.

You can further ask any questions. Please note that this sequence is not definite. Since we are designing this software as a group, all aspects of these sequences are design choices.

**Comment by meminciftci** [comment]
I have some questions about the path you mentioned:
- For the step 2, I could not find a find() method for Users class. Did you mean get() method? Also isn't it more appropriate to have Users class connected to registered user class since only registered users' actions are being recorded? Is there a reason behind putting it down to User class rather that Registered User class?

@tenacke

**Comment by tenacke** [comment]
You are right. It is get() method which I mentioned. There is no specific reason behind linking Users to User rather than RegisteredUser. I do not think this link will jeopardize the sequences. I thought we would need to access a guest user in the future. At this step, there is no use case relevant to this access so the link can be changed. I prefer to leave the link as it is now.
