### ISSUE TITLE
Update UML Diagrams

### ISSUE THREAD

**Issue by ozankrkya** [bounswe/bounswe2024group11#284]
# 🧱 Description

UML Diagrams shall be updated with newly agreed formats.

## 📋 Acceptance Criteria

- [ ] Use Case Diagram is reviewed and updated.
- [ ] Class Diagram is reviewed and updated.
- [ ] Sequence Diagrams are reviewed and updated.

**Comment by hks1444** [comment]
I updated [sequence diagram](https://github.com/bounswe/bounswe2024group11/wiki/Sequence-Diagrams) and [class diagram](https://github.com/bounswe/bounswe2024group11/wiki/Class-Diagrams). You can check them.

**Comment by MucahitErdoganUnlu** [comment]
I moved the user functionalities such as follow, block from RegisteredUser class to UserController class. And I moved the post functionalities such as like, bookmark from Post class to ContentController class so that the actions can be saved to the database.
I updated the sequence diagrams accordingly.

**Comment by MucahitErdoganUnlu** [comment]
I finalized them. Removed comments from diagrams and requirements. updated sequence diagrams to comply with use case diagrams
