### ISSUE TITLE
Relocate Gitignore and Get Rid of Workflows

### ISSUE THREAD

**Issue by meminciftci** [bounswe/bounswe2024group11#464]
# 🧱 Description

Old workflows directory shall be got ridden.  Also, gitignore file should be relocated.

## 📋 Acceptance Criteria

- [x] Delete `/.github/workflow` directory.
- [x] Relocate `.gitignore` file.

**Comment by Meminseeker** [comment]
I have a note about your issue style though.
1. Use imperative language in your acceptance criteria. Such as 'Relocate .gitignore file'
2. When you state a directory or file, be sure anyone can understand the correct artifact. Such as `/.github/workflow` directory. Otherwise people can't find where this directory is located.

**Comment by meminciftci** [comment]
Style is fixed. 

@Meminseeker

**Comment by Meminseeker** [comment]
It seems good. I also checked the activities. I'm closing the issue.
