### ISSUE TITLE
Organize Wiki page

### ISSUE THREAD

**Issue by Meminseeker** [bounswe/bounswe2024group11#465]
# 🧱 Description

The Wiki page of the repository is old and reflects the work done in the previous semester. It should be cleaned.
Please DO NOT remove the old documents. Just remove their references on the home page and on the sidebar.

## 📋 Acceptance Criteria

- [x] Clean the home page
- [x] Clean the sidebar

**Comment by MucahitErdoganUnlu** [comment]
I have removed irrelevant resources on the sidebar. But I left relevant resources such as [How to Initialize a Backend App Using Django REST Framework](https://github.com/bounswe/bounswe2024group11/wiki/How-to-initialize-a-backend-app-using-Django-REST-Framework) because they will be useful for this semester as well.

You can access the sidebar on [home page](https://github.com/bounswe/bounswe2024group11/wiki)

**Comment by meminciftci** [comment]
I have reformatted the home page according to new term. 

You can access the home page [here](https://github.com/bounswe/bounswe2024group11/wiki/Home)

**Comment by ArdaVural** [comment]
Wiki page looks completed and renewed. Thanks.

**Comment by Meminseeker** [comment]
I see some items on the sidebar that has `UPDATE LINK` text next to it. If something is not ready to to be shown by people, please comment those lines and be sure they are not visible by third eyes.

I'm reopening the issue. Update the sidebar.

**Comment by Meminseeker** [comment]
The sidebar seems good.
