### ISSUE TITLE
Implement related forum questions for a forum question

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#708]
# 🧱 Description
The forum questions have tags that enable us to semantically link them. We should provide semantically related forum questions by their tags. At most 5 of the related forum questions, sorted by latest, should be returned. These related forum questions should be included in a new field for the `detail` view/serializer of the forum question (if it is also included in the `list` view, this would create a burden on the request, resulting in a slow response). The logic of the semantically related forum questions is the same as the one used in semantic search endpoint: a tag (of the main forum question) is given to a function that returns the semantically related tags, and the forum questions are scanned and the ones that contains this tag is returned.

**Comment by meminciftci** [comment]
It is important that the semantically related forum questions are not fetched automatically. Only after sending a GET request by the id of the forum question, we shall also fetch the semantically related forum questions to that one. This will help us get rid of the overhead caused by the semantic search for forum question tags.
